### ISSUE TITLE
Please learn it properly

### ISSUE THREAD

**Issue by aneesh-neelam** [IEEECS-VIT/learn#1]
Hi! To those who do not know who I am, this is Aneesh Neelam (@aneesh-neelam). 

Learning how to use Git is well and good. However, please do learn how to make your commits more understandable as well. After all, this is for people to understand. 

Check out the book, [Pro Git](https://git-scm.herokuapp.com/book/en/v2). It is the best and only resource you need for Git.

**Comment by kunagpal** [comment]
Just for the record, all of this was discussed during the in-core session on Friday.

**Comment by aneesh-neelam** [comment]
OK. Carry on. :+1:
